name: Test Coverage

on:
  push:
    branches:
      - '**'

jobs:
  run-coverage:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /home/xgrid/GooseTest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Goose recipe
        run: goose run --recipe recipe.yaml --no-session
