name: Test Coverage

on:
  push:
    branches:
      - '**'

jobs:
  run-coverage:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t goose-test-coverage .

      - name: Run Goose recipe in Docker
        env:
          TETRATE_API_KEY: ${{ secrets.TETRATE_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          docker run --rm \
            -e TETRATE_API_KEY="${TETRATE_API_KEY}" \
            -e ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY}" \
            goose-test-coverage
