name: Test Coverage

on:
  push:
    branches:
      - '**'

jobs:
  run-coverage:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Goose recipe
        run: /home/xgrid/bin/goose run --recipe recipe.yaml --no-session
