name: Test Coverage

on:
  push:
    branches:
      - '**'

jobs:
  run-coverage:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t goose-test-coverage .

      - name: Run Goose recipe in Docker
        run: |
          docker run --rm \
            -e TETRATE_API_KEY="sk-c7d1f9d2fb8ff04a.fqtpodxehpbshIaH8hj/vw2REFRo5ubGaAuH1mRR7ha6WqijZgGCYNMkUIa7d7HVFp6Ypl81q0rbgR/9nT4/rA==" \
            goose-test-coverage